### ISSUE TITLE
datapack overflow

### ISSUE THREAD

**Issue by dfmjndm** [neon-nyan/CollapseLauncher#30] opened 2022-10-02 04:03 UTC
![image](https://user-images.githubusercontent.com/57401901/193437115-3bc1bae0-b0fd-4865-9a11-d056483f4a16.png)
![image](https://user-images.githubusercontent.com/57401901/193437392-5c6a4d5c-8f7e-4eb4-aefc-5cc738122795.png)

The packet size exceeded expectations, and when I paused the download, the application asked me to redownload the entire game（or the packet size dropped to 1GB）.Another situation, when the download size reached 18GB, the program flaked out during the data merge, and when I re-ran the program, it also asked me to re-download the entire game.So where the finished 18GB  data went. I wasted a lot of time in the installation process.
My platform -- Win10 21H2
Program version --1.0.36.3 stable （download from Readme.md）

**Comment by dfmjndm** [comment] 2022-10-02 04:11
Attach one of the program error:

Hi3Helper.Http.HttpHelperUnhandledError: Unhandled exception while downloading has occured!
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'from')
   at System.Net.Http.Headers.RangeItemHeaderValue..ctor(Nullable`1 from, Nullable`1 to)
   at System.Net.Http.Headers.RangeHeaderValue..ctor(Nullable`1 from, Nullable`1 to)
   at Hi3Helper.Http.Http.GetSessionMultisession(SessionAttribute Session) in C:\myGit\CollapseLauncher-fix20220911\Hi3HelperCore.Http\Class\Session.cs:line 53
   at Hi3Helper.Http.Http.RetryableTaskContainer(SessionAttribute Session, Boolean IsMultisession) in C:\myGit\CollapseLauncher-fix20220911\Hi3HelperCore.Http\Class\Thread.cs:line 73
   at Hi3Helper.Http.Http.StartRetryableTask(SessionAttribute Session, Boolean IsMultisession) in C:\myGit\CollapseLauncher-fix20220911\Hi3HelperCore.Http\Class\Thread.cs:line 109
   at Hi3Helper.Http.Http.TryAwaitOrDisposeStreamWhileFail(Task InnerTask, SessionAttribute Session) in C:\myGit\CollapseLauncher-fix20220911\Hi3HelperCore.Http\Class\Thread.cs:line 115
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'from')
   at System.Net.Http.Headers.RangeItemHeaderValue..ctor(Nullable`1 from, Nullable`1 to)
   at System.Net.Http.Headers.RangeHeaderValue..ctor(Nullable`1 from, Nullable`1 to)
   at Hi3Helper.Http.Http.GetSessionMultisession(SessionAttribute Session) in C:\myGit\CollapseLauncher-fix20220911\Hi3HelperCore.Http\Class\Session.cs:line 53
   at Hi3Helper.Http.Http.RetryableTaskContainer(SessionAttribute Session, Boolean IsMultisession) in C:\myGit\CollapseLauncher-fix20220911\Hi3HelperCore.Http\Class\Thread.cs:line 73
   at Hi3Helper.Http.Http.StartRetryableTask(SessionAttribute Session, Boolean IsMultisession) in C:\myGit\CollapseLauncher-fix20220911\Hi3HelperCore.Http\Class\Thread.cs:line 109
   at Hi3Helper.Http.Http.TryAwaitOrDisposeStreamWhileFail(Task InnerTask, SessionAttribute Session) in C:\myGit\CollapseLauncher-fix20220911\Hi3HelperCore.Http\Class\Thread.cs:line 115
   --- End of inner exception stack trace ---
   at Hi3Helper.Http.Http.TryAwaitOrDisposeStreamWhileFail(Task InnerTask, SessionAttribute Session) in C:\myGit\CollapseLauncher-fix20220911\Hi3HelperCore.Http\Class\Thread.cs:line 128
   at Hi3Helper.Http.Http.DownloadMultisession(String URL, String OutPath, Boolean Overwrite, Byte Sessions, CancellationToken Token) in C:\myGit\CollapseLauncher-fix20220911\Hi3HelperCore.Http\HttpMultisession.cs:line 31
   at CollapseLauncher.InstallManagement.StartDownloadAsync() in C:\myGit\CollapseLauncher-fix20220911\CollapseLauncher\Classes\InstallManagement\InstallManagement.cs:line 185
   at CollapseLauncher.Pages.HomePage.DownloadGameClient(String destinationFolder) in C:\myGit\CollapseLauncher-fix20220911\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 579
   at CollapseLauncher.Pages.HomePage.StartInstallationProcedure(String destinationFolder) in C:\myGit\CollapseLauncher-fix20220911\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 459
   at CollapseLauncher.Pages.HomePage.InstallGameDialog(Object sender, RoutedEventArgs e) in C:\myGit\CollapseLauncher-fix20220911\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 408

**Comment by neon-nyan** [comment] 2022-10-02 08:39
Thanks for reporting this issue.
I could confirm that this issue is caused by one of submodule used for this launcher, which is ``Hi3Helper.Http``
I'm currently trying to refactor the entire code of it and hopefully will be completed in the next 2 days or sonner.

**Comment by neon-nyan** [comment] 2022-10-04 15:53
This issue should've been addressed in the latest code changes.
The fix for this issue will be arrived in the next preview build.

I will close this issue at the moment.

**Closed by neon-nyan** 2022-10-04 15:53 UTC
Labels: Bug, Area: Hi3Helper.Http
