### ISSUE TITLE
Disable region change popup

### ISSUE THREAD

**Issue by wafflebot2143** [neon-nyan/CollapseLauncher#54] opened 2022-11-27 04:45 UTC
Greetings. When switching from Honkai to Genshin or vice versa, a popup says that the game region will be changed even when the region is the same. I have never installed or played either game on servers other than the global server, so I'd like to request the option to disable this popup and streamline switching games.

**Comment by neon-nyan** [comment] 2022-11-27 09:14
Thank you for your suggestion on this.
However, this has been issued and a duplicate of #18.
I think we will implement a toggle to disable this confirmation dialog in the future.

For now, we will be tracking this suggestion on Issue No. #18.

**Closed** 2022-11-27 09:16 UTC
Labels: Duplicate, Enhancement, Area: UI/UX
