### ISSUE TITLE
[BUG] Cache update not working

### ISSUE THREAD

**Issue by muscularcandy67** [neon-nyan/CollapseLauncher#22] opened 2022-09-19 07:11 UTC
When trying to use Caches Update for Honkai this is what happens since the 6.0 update
![image](https://user-images.githubusercontent.com/12277635/190966258-dba2c77e-4960-40c5-8c84-e6312e145049.png)

**Here is the error log copied in a txt file for an easier way to read it**
[CollapseLauncher_CachesUpdate_Error.txt](https://github.com/neon-nyan/CollapseLauncher/files/9596758/CollapseLauncher_CachesUpdate_Error.txt)

**Comment by neon-nyan** [comment] 2022-09-19 09:55
I could confirm that this is a known issue. The cache update mechanism depends on the API inside of Hi3Mirror project and unfortunately, the server is currently down and causing some functionalities like Caches Update, Game Repair and Game Conversion wouldn't be working temporarily.

But the good thing is, the server will be back up on September 21st and hopefully those feature will be back online.

Anyway, I'm planning to make those functionalities to work independently from Hi3Mirror project in the next stable release.

**Comment by neon-nyan** [comment] 2022-09-22 02:50
Hi there,

Hi3Mirror is now back online.
Please try to access the Update Cache and Game Repair menu once again and make sure if it works properly now.

**Comment by muscularcandy67** [comment] 2022-09-22 14:18
I tried and so far it's not working

**Comment by neon-nyan** [comment] 2022-09-23 01:37
I just checked this last night and confirmed there's something wrong with the ``DispatcherQueue``. I hope I can push the fix commit tonight

**Comment by muscularcandy67** [comment] 2022-09-23 16:27
I went ahead and compiled the last commit 73337434bd75e2673d11cdaac7775c388261bf2c and I can say the caches update function works. I won't go ahead and close the issue since you might be testing other stuff for this commit

**Comment by neon-nyan** [comment] 2022-09-25 02:16
Hi there,
Yes, there are some other commit that will be pushed later. But for this issue itself, that commit is enough for the fix.
I will push the next preview release tonight (at GMT+7 time-zone) with the fix from that commit.

**Comment by neon-nyan** [comment] 2022-09-26 12:59
Sorry for the late follow up.
I should've supposed to publish the next preview release 2 days ago but forgot since I have many things to do.

The new preview build is out now with the fix for this issue.
https://github.com/neon-nyan/CollapseLauncher/releases/tag/CL-v1.0.40.8-pre

**Comment by neon-nyan** [comment] 2022-10-04 15:44
Since this issue has been already solved in v1.0.40.9-pre build, I will go ahead to close this issue.

**Closed by neon-nyan** 2022-10-04 15:44 UTC
Labels: Bug, Game: Honkai Impact 3rd, Area: Mirror/API Server
