### ISSUE TITLE
Error pops out when repairing the game 

### ISSUE THREAD

**Issue by DarkXonline** [neon-nyan/CollapseLauncher#17] opened 2022-09-09 14:56 UTC
![image](https://user-images.githubusercontent.com/22949719/189379915-192bff9e-7667-4efd-ad24-198ad281d216.png)

```Hi3Helper.Http.HttpHelperUnhandledError: Unhandled exception while downloading has occured!
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'from')
   at System.Net.Http.Headers.RangeItemHeaderValue..ctor(Nullable`1 from, Nullable`1 to)
   at System.Net.Http.Headers.RangeHeaderValue..ctor(Nullable`1 from, Nullable`1 to)
   at Hi3Helper.Http.Http.GetSession(SessionAttribute Session) in C:\myGit\CollapseLauncher-fix20220825\Hi3HelperCore.Http\Class\Session.cs:line 20
   at Hi3Helper.Http.Http.RetryableTaskContainer(SessionAttribute Session, Boolean IsMultisession) in C:\myGit\CollapseLauncher-fix20220825\Hi3HelperCore.Http\Class\Thread.cs:line 70
   at Hi3Helper.Http.Http.StartRetryableTask(SessionAttribute Session, Boolean IsMultisession) in C:\myGit\CollapseLauncher-fix20220825\Hi3HelperCore.Http\Class\Thread.cs:line 84
   at Hi3Helper.Http.Http.TryAwaitOrDisposeStreamWhileFail(Task InnerTask, SessionAttribute Session) in C:\myGit\CollapseLauncher-fix20220825\Hi3HelperCore.Http\Class\Thread.cs:line 115
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'from')
   at System.Net.Http.Headers.RangeItemHeaderValue..ctor(Nullable`1 from, Nullable`1 to)
   at System.Net.Http.Headers.RangeHeaderValue..ctor(Nullable`1 from, Nullable`1 to)
   at Hi3Helper.Http.Http.GetSession(SessionAttribute Session) in C:\myGit\CollapseLauncher-fix20220825\Hi3HelperCore.Http\Class\Session.cs:line 20
   at Hi3Helper.Http.Http.RetryableTaskContainer(SessionAttribute Session, Boolean IsMultisession) in C:\myGit\CollapseLauncher-fix20220825\Hi3HelperCore.Http\Class\Thread.cs:line 70
   at Hi3Helper.Http.Http.StartRetryableTask(SessionAttribute Session, Boolean IsMultisession) in C:\myGit\CollapseLauncher-fix20220825\Hi3HelperCore.Http\Class\Thread.cs:line 84
   at Hi3Helper.Http.Http.TryAwaitOrDisposeStreamWhileFail(Task InnerTask, SessionAttribute Session) in C:\myGit\CollapseLauncher-fix20220825\Hi3HelperCore.Http\Class\Thread.cs:line 115
   --- End of inner exception stack trace ---
   at Hi3Helper.Http.Http.TryAwaitOrDisposeStreamWhileFail(Task InnerTask, SessionAttribute Session) in C:\myGit\CollapseLauncher-fix20220825\Hi3HelperCore.Http\Class\Thread.cs:line 128
   at Hi3Helper.Http.Http.DownloadStream(String URL, Stream OutStream, CancellationToken Token, Int64 Start, Nullable`1 End) in C:\myGit\CollapseLauncher-fix20220825\Hi3HelperCore.Http\Http.cs:line 49
   at CollapseLauncher.Pages.RepairPage.RepairBlockFiles(FilePropertiesRemote input) in C:\myGit\CollapseLauncher-fix20220825\CollapseLauncher\Classes\RepairManagement\DataRepair.cs:line 158
   at CollapseLauncher.Pages.RepairPage.CategorizeRepairAction() in C:\myGit\CollapseLauncher-fix20220825\CollapseLauncher\Classes\RepairManagement\DataRepair.cs:line 64
   at CollapseLauncher.Pages.RepairPage.StartGameRepair(Object sender, RoutedEventArgs e) in C:\myGit\CollapseLauncher-fix20220825\CollapseLauncher\Classes\RepairManagement\DataRepair.cs:line 31```

**Comment by neon-nyan** [comment] 2022-09-10 10:52
Seems like this is an issue with the Hi3Helper.Http submodule. I will look into that later because I'm currently away now and will be back on Sept 11th.

**Comment by neon-nyan** [comment] 2022-09-11 12:36
I just investigated the issue and turns out, the issue was caused by the ``EndOffset`` by this piece of code in ``Hi3Helper.Http`` submodule:

https://github.com/neon-nyan/Hi3Helper.Http/blob/5e9e8d2d583b78db3127a0934fa7b18ccd14b623/Class/Session.cs#L20

The ``EndOffset`` is not checkedn while getting set to -1 and leave it as is. Instead, it will give the value -2 and causing invalid range.
![image](https://user-images.githubusercontent.com/30566970/189527830-1d389f1f-77dc-4324-aa13-fa5eaaa3ec37.png)
Anyway, I'm planning to make a hotfix for this later or as soon as possible so,... wait for it while I'm trying to make a fix for this 😃

**Comment by neon-nyan** [comment] 2022-09-11 14:18
## Update
This issue should've been fixed on the new 1.0.36.3-Hotfix update.
Please update your launcher to fix this issue and you can consider close this issue if you feel that this issue has been solved.

Once again, thank you for reporting this.

**Comment by DarkXonline** [comment] 2022-09-11 14:25
Where is the 1.0.36.3-Hotfix update? I would like to try it out
Couldn't find it on Release
![image](https://user-images.githubusercontent.com/22949719/189532753-e20f38cf-958c-4ba4-9dc8-749e84560a3c.png)

**Comment by neon-nyan** [comment] 2022-09-11 14:29
@DarkXonline the update on GitHub page hasn't been published.
You can do update inside of the launcher.

Go to App Settings -> Scroll down and click **Check Update** button
![image](https://user-images.githubusercontent.com/30566970/189532970-267e2874-6fec-4f47-ad18-6a1514c502cd.png)

**Comment by DarkXonline** [comment] 2022-09-11 14:30
> @DarkXonline the update on GitHub page hasn't been published. You can do update inside of the launcher.
> 
> Go to **App Settings** menu -> Scroll down and click **Check Update** button ![image](https://user-images.githubusercontent.com/30566970/189532970-267e2874-6fec-4f47-ad18-6a1514c502cd.png)

I see, I will update now :D

**Closed** 2022-09-11 14:32 UTC
Labels: Bug, Fixed, Area: Hi3Helper.Http
